# Site settings
title: Christian Hoffmeister
email: mail@choffmeister.de
description: >
  This is a personal blog of mine where I will post about
  mostly technical things I stumble upon in my daily professional
  as well as personal life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://choffmeister.de" # the base hostname & protocol for your site
twitter_username: thekwasti
github_username:  choffmeister
permalink: /posts/:year/:month/:day/:title.html
googleanalytics_id: UA-37878676-2

# Build settings
markdown: kramdown
